name: Update model config
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: ".ci/requirements.txt"
      - name: Run tests
        run: chmod +x tests.sh && ./tests.sh
      - name: Upload to gcloud
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJ_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD }}
        with:
          args: cp -r models.config gs://${{ secrets.EXPORT_PLATFORM }}
          cli: gsutil