name: Deploy web to production
on:
  push:
    branches:
      - 'web_page'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: 'web_page'
      - name: Run tests
        run: tests.py