name: Deploy web to production
on:
  push:
    branches:
      - 'web_page'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: 'web_page'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run tests
        run: chmod +x tests.sh && ./tests.sh
